name: Django SAST Pipeline
# testing 2
on:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  NonProd-SAST-scan:
    uses: marekboodt/Security-Scanning-Repo/.github/workflows/sast-workflow.yml@main
    with:
      language: python
      project_dir: ./src
      # non-prod has 'continue-on-error: true' all other environments will be stopped if the scans give an error.
      environment: non-prod
#    secrets:
#      token: ${{ secrets.REUSABLEWORKFLOWACCESSDJANGOTOSECREPO }}

  Prod-SAST-scan:
    uses: marekboodt/Security-Scanning-Repo/.github/workflows/sast-workflow.yml@main
    with:
      language: python
      project_dir: ./src
      # non-prod has 'continue-on-error: true' all other environments will be stopped if the scans give an error.
      environment: prod
