name: Django SAST Pipeline
# testing multiple location
on:
  push:
    branches:
      - main

jobs:
  trigger-sast-scan:
    uses: marekboodt/Security-Scanning-Repo/.github/workflows/workflow.yml@main
    with:
      language: python       # Specify the language for the scan
      project_dir: ./src     # Directory in the Django.nv repo to scan
      environment: non-prod  # Specify the environment (e.g., non-prod or prod)
    secrets:
      token: ${{ secrets.SECURITY_REPO_TOKEN }}
