name: Django SAST Pipeline
# test
on:
  push:
    branches:
      - main

jobs:
  trigger-sast-scan:
    uses: marekboodt/Security-Scanning-Repo/.github/workflows/sast-workflow.yml@main
    with:
      language: python
      project_dir: ./src
      environment: non-prod
    secrets:
      token: ${{ secrets.SECURITY_REPO_TOKEN }}
