name: Django Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 1'   # Monday at 02:00 UTC

permissions:
  actions: read
  contents: read
  security-events: write
  
jobs:
  SAST-Scan-semgrep:
    uses: marekboodt/Security-Scanning-Repo/.github/workflows/10-sast-workflow.yml@v1
    with:
      sast-scan-tool: semgrep
      project_dir: ./src
      environment: non-prod
    secrets:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
      # SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      # SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

  SAST-Scan-bearer:
    uses: marekboodt/Security-Scanning-Repo/.github/workflows/10-sast-workflow.yml@v1
    with:
      sast-scan-tool: bearer
      project_dir: ./src
      environment: non-prod
    # secrets:
      # SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      # SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
      
  SAST-Scan-codeql:
    uses: marekboodt/Security-Scanning-Repo/.github/workflows/10-sast-workflow.yml@v1
    with:
      sast-scan-tool: codeql
      project_dir: ./src
      environment: non-prod
    # secrets:
      # SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      # SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
