name: Testing Reusable Workflows Multi Repo
#  test
on:
  push:
    branches:
      - main
  workflow_dispatch:

#jobs:
  # location of the folder to use. 
#  trigger-reusable-Workflow:
#    uses: marekboodt/Security-Scanning-Repo/.github/workflows/SSR_test_workflow.yml@main 
#    with:
#      message: "Hello from django.nv!"

### Other workflows 
#  Sast-Scan-Workflow:
#    uses: marekboodt/Security-Scanning-Repo/.github/workflows/sast-workflow.yml@main
#    with:
#      language: python
#      project_dir: ./src
#      environment: non-prod
